VISUAL_MODE = True
TEST = False
PRINT_GENOME = False
WRITE_GENOME = True
SENSOR = 0
NEURON = 1
ACTION = 2
NUM_SENSES = 7 #Needs to match sensor_inputs in `run`
NUM_ACTIONS = 3 #Should match action steps in `simulation`
log_file = 'log.txt'
MAX_NEURONS = 20
GENOME_LENGTH = 40
POPULATION_SIZE = 3 if TEST else 20
SPEED = 8 if TEST else 80
GENERATION_STEPS = 100
MUTATION_RATE = 0.1
