TEST = False
PRINT_GENOME = False
WRITE_GENOME = False
SENSOR = 0
NEURON = 1
ACTION = 2
NUM_SENSES = 7 #Needs to match sensor_inputs in `run`
NUM_ACTIONS = 2 #Should match action steps in `simulation`
log_file = 'log.txt'
VISUAL_MODE = True
MAX_NEURONS = 25
GENOME_LENGTH = 60
POPULATION_SIZE = 3 if TEST else 20
SPEED = 8 if TEST else 80
GENERATION_STEPS = 100
MUTATION_RATE = 0.1
